config/routes.rb
As1::Application.routes.draw do
  devise_for :users
  resources :projects do 
    get :favorites, on: :collection
    resources :votes, only:[:create] do
      delete :remove, on: :collection
    end
  end

  post 'login' => 'projects#login'
  post 'logout' => 'projects#logout'
  

  resources :discussions do
    post :flag, on: :member
  end

  
  root 'projects#index'
  post 'projects/:id' => 'projects#addlike'
  

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

	validates_presence_of :title, message: "should be provided."
	validates_uniqueness_of :title, message: "should be unique."
	validates :title, length: {minimum: 10, message: "should be at least 10 characters."}
	validates :description, presence: true
	validates_numericality_of :hits, allow_nil: true
	
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
	before_action :set_disc, only: [:edit, :update, :show,:destroy, :addlike, :flag]
  layout "discussions"
	def index
		@discussions=Discussion.order ("hits DESC")
	end
	
	def new
		@discus=Discussion.new
	end

	def create
		@discus=Discussion.new params.require(:discussion).permit([:title,:description])
		if @discus.save
			redirect_to discussions_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @discus.update_attributes params.require(:discussion).permit([:title,:description])
			redirect_to discussions_path
		else
			render :edit
		end
	end

	def show
		@discus.hits||=0
		@discus.hits+=1
		@discus.save
	end

	def destroy 
		@discus.destroy
		redirect_to discussions_path
	end

  def flag
    render :show
  end

	private

	def set_disc
		@discus=Discussion.find(params[:id])
	end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_for @discus do |f| %>
	<% if @discus.errors.any? %>
		<ul>
		<% @discus.errors.full_messages.each do |message| %>
			<li c><%= message %></li>
		<% end %>
		</ul>
	<% end %>
	<div><%= f.label :title, "Discussion's title" %>
	<br>
	<%= f.text_field :title%>
	</div>
	<br>
	<div>
	<%= f.label :description, "Discussion's description" %>
	<br>
	<%= f.text_area :description  %>
	</div>
	<br>
	<%= f.submit "Save" %>

<% end %>

app/views/discussions/edit.html.erb
<%= render "form" %>

<%= link_to "Index",discussions_path,class: 'btn btn-default' %>
<%= link_to "Remove",discussion_path, method: 'delete',confirm: "Are you sure you want to remove discussion "+(@discus.id).to_s+"?",class: 'btn btn-default' %>

app/views/discussions/index.html.erb
<h1>Discussions</h1>
<table>
	<th>Title</th>
	<th>Description</th>
	<th>Hits</th>
	<% @discussions.each do |discussion| %>
	<tr>
	<td> <%= link_to discussion.title, discussion %> </td>
	<td> <%= discussion.description %></td>
	<td> <%=discussion.hits %></td>
	<td><%= link_to "Edit",edit_discussion_path(discussion),class: 'btn btn-default' %></td>
	<td><%= link_to "Remove",discussion_path(discussion), method: 'delete',confirm: "Are you sure you want to remove discussion "+(discussion.id).to_s+"?",class: 'btn btn-default' %></td>
	</tr>
	<% end %>
</table>
<%= link_to "New",new_discussion_path,class: 'btn btn-default' %>
<%= link_to "Projects",projects_path,class: 'btn btn-default' %>

app/views/discussions/new.html.erb
<%= render "form" %>
<%= link_to "Index",discussions_path,class: 'btn btn-default' %>

app/views/discussions/show.html.erb
<h1> <%= @discus.title %></h1>
<p> <%= @discus.description %></p>
<%= link_to "Index",discussions_path,class: 'btn btn-default' %>
<%= link_to "Edit",edit_discussion_path,class: 'btn btn-default' %>