config/routes.rb
As1::Application.routes.draw do
  devise_for :users
  resources :projects do 
    get :favorites, on: :collection
    resources :votes, only:[:create] do
      delete :remove, on: :collection
    end
  end

  post 'login' => 'projects#login'
  post 'logout' => 'projects#logout'
  

  resources :discussions do
    post :flag, on: :member
  end

  
  root 'projects#index'
  post 'projects/:id' => 'projects#addlike'
  

end

app/models/project.rb
class Project < ActiveRecord::Base

	attr_accessor :terms

	has_many :categorizations, dependent: :destroy
	has_many :categories, through: :categorizations
	has_many :votes, dependent: :destroy
	has_many :voters, through: :votes, source: :user
	scope :hitorder, -> {order('hits DESC')}
	scope :likeorder, -> {order('likes DESC')}
	scope :nmostrs, lambda{|n| order("created_at DESC").limit(n)}
	
	# before_save :cap_it_all
	after_save :print_message
	before_create :cap_it_all

	
	validates_presence_of :title, message: "should be provided."
	validates_uniqueness_of :title, message: "should be unique."
	validates :title, length: {minimum: 10, message: "should be at least 10 characters."}
	validates :description, presence: true
	validates :terms, acceptance: {accept: 'does',message: "must be accepted."}
		

	private

	def cap_it_all
		self.title.capitalize!
		self.description.capitalize!
	end

	def print_message
		Rails.logger.info "This is a message"
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_proj, only: [:edit, :update, :show,:destroy, :addlike]
	before_action :print_id, except: [:new, :index]
	# before_action :boot_out, only: [:edit,:update,:create,:new,:destroy,:addlike]
	before_action :authenticate_user!, only: [:create,:update,:destroy,:current_users_vote,:current_user_voted]
	def index
		# elders=Project.order("created_at DESC")[3..-1]
		# elders||=[]
		@projects=Project.nmostrs(5)
		# @projects=[]
		# projs.each do |proj|
		# 	if elders.include? proj
		# 		@projects.push proj
		# 	end
		# end
		@recent_projs=Project.order("created_at DESC")[0..2]
		ids=[]
		@recent_projs.each do |rec|
			ids << rec[:id]
		end

		# ids=@recent_projs["Project"][:id]
		# @projects=@projects.select{|x| !ids.include?(x[:id])}
		# @recent_projs.each do |del|
		# 	@projects.delete(del)
		# end
	end
	
	def new
		@proj=Project.new
	end

	def create

		@proj=Project.new params.require(:project).permit([:title,:description,:terms,{category_ids:[]}])
		print @proj
		#@proj.terms=params[:terms]
		#p @proj
		if @proj.save
			print @proj
			redirect_to projects_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		# @proj.title=params[:project][:title]
		# @proj.description=params[:project][:description]
		# @proj.save
		if @proj.update_attributes params.require(:project).permit([:title,:description,{category_ids:[]}])
			redirect_to projects_path
		else
			render :edit
		end
	end

	def show
		@proj.hits||=0
		@proj.hits+=1
		@proj.save
		if user_upped
			@vote_cond='upped'
		elsif user_downed
			@vote_cond='downed'
		else
			@vote_cond='none'	
		end	
	end

	def destroy 
		@proj.destroy
		redirect_to projects_path
	end

	def addlike
		par_id=params[:id]
		session[:likes]||=Array.new
		#if session[:likes] != nil
		if session[:likes].include? par_id
			redirect_to project_path, alert: "You have already liked."
			return
		end
		# (session[:likes].include? par_id)? Proc.new{
		# 	redirect_to project_path, alert: "You have already liked."
		# 	#puts "FEFEFFEFFEFEWFWEFEW"
		# 	return}.call
		# 	: nil
		# 	redirect_to project_path
		# 	return
		# end
			# session[:likes].each do |id|
			# 	if par_id==id
			# 		redirect_to project_path
			# 		return
			# 	end
			# end
		# else
		# 	session[:likes]=Array.new
		# end
		session[:likes].push(par_id)
	  @proj.like+=1
	  @proj.save
	  redirect_to project_path, notice: "Thanks for liking"
	end

	def favorites
	end

	def login
		session[:loggedin]='true'
		redirect_to :back
	end

	def logout
		session[:loggedin]='false'
		redirect_to projects_path
	end

	def user_upped
		current_user_voted && current_users_vote=='up'
	end

	def user_downed
		current_user_voted && current_users_vote=='down'
	end

	private

	def current_users_vote
		@proj.votes.find_by(user_id: current_user).vote_kind
	end

	def current_user_voted
		@proj.voters.include? current_user
	end

	def boot_out
		if session[:loggedin]!='true'
			redirect_to projects_path, alert: "You have to be logged in"
		end
	end

	def print_id
		Rails.logger.info "------------"
		Rails.logger.info params[:id]
		Rails.logger.info "------------"
	end
	
	def set_proj 
		@proj=Project.find(params[:id])
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @proj do |f| %>
	<% if @proj.errors.any? %>
		<ul>
		<% @proj.errors.full_messages.each do |message| %>
			<li class='rederror'><%= message %></li>
		<% end %>
		</ul>
	<% end %>
	<div><%= f.label :title, "Project's title" %>
	<br>
	<%= f.text_field :title%>
	</div>
	<br>
	<div>
	<%= f.label :description, "Project's description" %>
	<br>
	<%= f.text_area :description  %>
	</div>
	<br>
	<%= hidden_field_tag "project[category_ids][]",nil %>
	<% Category.all.each do |cat| %>
		<%= check_box_tag "project[category_ids][]",cat.id, @proj.categories.include?(cat),id: dom_id(cat) %>
		<%= label_tag dom_id(cat), cat.name %>
	<% end %>
	<% if !@proj.persisted? %>
	<div>
	<%= f.check_box("terms",{}, "does", "no")  %>
	<%= f.label :accept, "Accept or vanquish" %>
	</div>
	<% end %>
	<%= f.submit "Save" %>

<% end %>

app/views/projects/_test.html.erb
<table>
	<th>Title</th>
	<th>Description</th>
	<th>Count of Likes</th>
	<th>Hits</th>
<% @pp.each do |project| %>
<tr>
	<td> <%= link_to project.title, project %> </td>
	<td> <%= truncate_s(project.description,10) %></td>
	<td> <%= project.like %></td>
	<td> <%= project.hits %></td>
	<td><%= link_to "Edit",edit_project_path(project),class: 'btn btn-default' %></td>
	<td><%= link_to "Remove",project_path(project), method: 'delete',confirm: "Are you sure you want to remove project "+(project.id).to_s+"?",class: 'btn btn-default' %></td>
	<td><%= link_to "Like",project_path(project),class: 'btn btn-default', method:'post' %></td>
	</tr>
	<% end %>

</table>

app/views/projects/edit.html.erb
<%= render "form" %>
<%= link_to "Index",projects_path,class: 'btn btn-default' %>
<%= link_to "Remove",project_path,class: 'btn btn-default', method: 'delete',confirm: "Are you sure you want to remove project "+(@proj.id).to_s+"?" %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<h2>Projects by Hit Count</h2>
	<% @pp=@projects%>
	<%= render "test" %>

<h2> Three most Recent Projects</h2>

	<% @pp=@recent_projs %>
		<%= render "test" %>

<%= link_to "New",new_project_path,class: 'btn btn-default' %>
<%= link_to "Discussions",discussions_path,class: 'btn btn-default' %>

app/views/projects/new.html.erb
<%= render "form" %>

app/views/projects/show.html.erb
<h1> <%= @proj.title %></h1>
<p> <%= @proj.description %></p>
<p> Number of likes: <%= @proj.like %></p>
<p> Number of Votes: <%= @proj.vote_count %></p>
<%= link_to "Index",projects_path,class: 'btn btn-default' %>
<%= link_to "Edit",edit_project_path,class: 'btn btn-default' %>
<% if @vote_cond=='upped' %>
	<%= form_tag(remove_project_votes_path(@proj), method: "delete") do%>
		<%=hidden_field_tag 'vote','upback'%>
		<%= submit_tag("Take back vote up",class: 'btn btn-default') %>
	<% end %>
<% else %>
	<%= form_tag(project_votes_path(@proj), method: 'post') do %>
		<%=hidden_field_tag 'vote','up'%>
		<%= submit_tag("Vote Up",class: 'btn btn-default') %>
	<% end %>
<% end %>

<%if @vote_cond=='downed'%>
	<%= form_tag(remove_project_votes_path(@proj), method: "delete") do%>
		<%=hidden_field_tag 'vote','downback'%>
		<%= submit_tag("Take back vote down",class: 'btn btn-default') %>
	<% end %>
<% else %>
	<%= form_tag(project_votes_path(@proj), method: 'post') do %>
		<%=hidden_field_tag 'vote','down'%>
		<%= submit_tag("Vote Down",class: 'btn btn-default') %>
	<% end %>
<% end %>

<% if (session[:likes].present? && session[:likes].include?(@proj.id.to_s)) %>
	<%= link_to "Liked",'javascript:void(0);',disabled: "disabled",class: 'btn btn-default' %>
<% else %>
	<%= link_to "Like",project_path(@proj), method:'post',class: 'btn btn-default' %>
<%end %>